stages:
  - build
  - deploy

variables:
  IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME

build-job:
  stage: build
  image:
    name: docker:stable
  services:
    - name: docker:dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - touch .env
  script:
    - docker build -t $IMAGE:web .
    - docker push $IMAGE:web
    - docker build -t $IMAGE:nginx ./nginx
    - docker push $IMAGE:nginx
  after_script:
    - docker logout

deploy-job:
  image: alpine
  stage: deploy
  tags:
    - deployment
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker-compose -f docker-compose.prod.yml pull
    - docker-compose -f docker-compose.prog.yml up -d
