stages:
  - build
  - deploy

variables:
  IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME

build-job:
  image: docker:19.03
  stage: build
  services:
    - docker:19.03-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - touch /builds/nomonovjahongirbek/metsenat/.env
  script:
    - docker build .
    - docker push $IMAGE:web
    - docker push $IMAGE:nginx
  after_script:
    - docker logout

deploy-job:
  image: alpine
  stage: deploy
  tags:
    - deployment
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker-compose -f docker-compose.prod.yml pull
    - docker-compose -f docker-compose.prog.yml up -d
